name: Generate SDK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Generate SDK
      run: |
        echo "Generating SDK"
        echo "$(date)" >> timestamp.txt

    - name: Copy SDK files to another repo and push
      env:
        DEPLOY_KEY: ${{ secrets.SDK_DEPLOY_KEY }}
      run: |
        mkdir ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name 'tiagokrebs'
        git config --global user.email 'tiago.krebs@azion.com'
        git clone git@github.com:krebsco/sdk.git sdk-repo
        cp -r * sdk-repo/
        cd sdk-repo
        git add .
        git commit -m "Generated new SDK version"
        git push
