name: Open Pull Request in Another Repo
on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 'krebsco/sdk'  # The repo where the PR should be created
          token: ${{ secrets.PAT }}  # Use your personal access token

      - name: Modify file
        run: echo "$(date)" >> timestamp.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: "Update data"
          title: "Update data"
          body: "This PR updates the data."
          branch: "test"  # The branch to create or update
          base: "main"  # The branch to target with the pull request
          labels: "automerge"
