name: Open and Merge PR

on:
  push:
    branches:
      - main

jobs:
  create-and-merge-pr:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PAT }}
        push-to-fork: tiagokrebs/sdk
        branch: create-pr-branch
        title: Create PR
        body: |
          This is an automated PR created from repo1.
        draft: false
        labels: automerge

    - name: Checkout target repo
      uses: actions/checkout@v2
      with:
        repository: tiagokrebs/sdk
        token: ${{ secrets.PAT }}
        
    - name: Auto merge
      uses: pascalgn/automerge-action@v0.14.3
      env:
        GITHUB_TOKEN: "${{ secrets.PAT }}"
        MERGE_LABELS: "automerge,!wip"
        MERGE_METHOD: "squash"
        MERGE_COMMIT_MESSAGE: "Automatic merge of PR from repo1"
        MERGE_FORKS: "true"
        UPDATE_LABELS: ""
